# this information can't be in the base directory
# different environments are going to want different replica count, different strategies
# thus this should be patched into the base, using Kustomize
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: action-pod 
  namespace: action-system 
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: action 
  template:
    metadata:
      labels:
        app: action 
    spec:
      containers:
      - name: action-api 
      # action-api container configuration 
        resources:
          limits:
            cpu: "2000m" # up to 2 full cores, a two CPU-bound Go program, GOMAXPROCS(0)=2
          requests:
            cpu: "1000m" # Use 1 full core