# Define a namespace for action
apiVersion: v1 
kind: Namespace
metadata:
  name: action-system 
---
# Deployment defines how I want the Pod configured and how it should run
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: action-pod # base Pod name
  namespace: action-system 
spec:
  selector:
    matchLabels:
      app: action 
  template:
    metadata:
      labels:
        app: action # Selector for Pod name search. Enables query by label on cmd line.
    spec:
      dnsPolicy: ClusterFirstWithHostNet 
      hostNetwork: true 
      terminationGracePeriodSeconds: 60
      # the containers to run in the Pod
      containers:
        # sales-api container configuration
      - name: action-api 
        # gets patched to the specific docker image name in kind/action-pod/kustomization.yaml
        # done to avoid hardcoding image name and version
        image: action-api-image
        # name the ports that the deployment needs to be aware of
        ports:
        - name: action-api 
          containerPort: 3000 
        - name: action-debug 
          containerPort: 4000 
        # hit readiness endpoint every 15 seconds on port 4000
        readinessProbe: 
          httpGet:
            path: /debug/readiness 
            port: 4000 
          initialDelaySeconds: 15 
          periodSeconds: 15 
          timeoutSeconds: 5 
          successThreshold: 1 
          failureThreshold: 2 
        # hit liveness endpoint every 30 seconds on port 4000
        livenessProbe:
          httpGet:
            path: /debug/liveness 
            port: 4000 
          initialDelaySeconds: 30 
          periodSeconds: 30 
          timeoutSeconds: 5 
          successThreshold: 1 
          failureThreshold: 2 
        # env will set the below env variables up so we can read them in our liveness handler
        env:
          - name: KUBERNETES_NAMESPACE 
            valueFrom:
              fieldRef: 
                fieldPath: metadata.namespace 
          - name: KUBERNETES_PODNAME 
            valueFrom: 
              fieldRef: 
                fieldPath: metadata.name 
          - name: KUBERNETES_NAMESPACE_POD_ID 
            valueFrom: 
              fieldRef: 
                fieldPath: status.podIP 
          - name: KUBERNETES_NODENAME 
            valueFrom:
              fieldRef: 
                fieldPath: spec.nodeName 
      - name: metrics 
        image: metrics-image 
        ports:
        - name: metrics 
          containerPort: 3001 
        - name: metrics-debug 
          containerPort: 4001
--- 
# Service definition exposes external ports and maps them to those above in the deployment
apiVersion: v1 
kind: Service 
metadata: 
  name: action-service 
  namespace: action-system 
spec: 
  type: ClusterIP 
  selector:
    app: action 
  ports:
  - name: action-api 
    port: 3000 
    targetPort: action-api 
  - name: action-debug 
    port: 4000 
    targetPort: action-debug
  - name: metrics 
    port: 3001 
    targetPort: metrics 
  - name: metrics-debug 
    port: 4001
    targetPort: metrics-debug